
model=PAttn

python run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/simulate/ \
    --data_path dependent02.csv \
    --model_id 'simulate_dp02_96_96' \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 0 \
    --pred_len 96 \
    --train_epochs 10 \
    --d_model 512 \
    --n_heads 8 \
    --e_layers 1 \
    --d_layers 1 \
    --d_ff 512 \
    --enc_in 3 \
    --c_out 3 \
    --patch_size 16 \
    --stride 8 \
    --itr 1 \
    --des 'Exp' \
    --factor 3 \
    --model $model \

python run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/simulate/ \
    --data_path dependent04.csv \
    --model_id 'simulate_dp04_96_96' \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 0 \
    --pred_len 96 \
    --train_epochs 10 \
    --d_model 512 \
    --n_heads 8 \
    --e_layers 1 \
    --d_layers 1 \
    --d_ff 512 \
    --enc_in 3 \
    --c_out 3 \
    --patch_size 16 \
    --stride 8 \
    --itr 1 \
    --des 'Exp' \
    --factor 3 \
    --model $model \

python run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/simulate/ \
    --data_path dependent06.csv \
    --model_id 'simulate_dp06_96_96' \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 0 \
    --pred_len 96 \
    --train_epochs 10 \
    --d_model 512 \
    --n_heads 8 \
    --e_layers 1 \
    --d_layers 1 \
    --d_ff 512 \
    --enc_in 3 \
    --c_out 3 \
    --patch_size 16 \
    --stride 8 \
    --itr 1 \
    --des 'Exp' \
    --factor 3 \
    --model $model \


python run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/simulate/ \
    --data_path dependent08.csv \
    --model_id 'simulate_dp08_96_96' \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 0 \
    --pred_len 96 \
    --train_epochs 10 \
    --d_model 512 \
    --n_heads 8 \
    --e_layers 1 \
    --d_layers 1 \
    --d_ff 512 \
    --enc_in 3 \
    --c_out 3 \
    --patch_size 16 \
    --stride 8 \
    --itr 1 \
    --des 'Exp' \
    --factor 3 \
    --model $model \


python run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/simulate/ \
    --data_path dependent10.csv \
    --model_id 'simulate_dp10_96_96' \
    --data custom \
    --features M \
    --seq_len 96 \
    --label_len 0 \
    --pred_len 96 \
    --train_epochs 10 \
    --d_model 512 \
    --n_heads 8 \
    --e_layers 1 \
    --d_layers 1 \
    --d_ff 512 \
    --enc_in 3 \
    --c_out 3 \
    --patch_size 16 \
    --stride 8 \
    --itr 1 \
    --des 'Exp' \
    --factor 3 \
    --model $model \
